import { compile } from 'path-to-regexp';

export const routes = {
  home: '/',
  login: '/login',
  dashboard: '/app/dashboard',
  audioNew: '/app/audio/new',
  audioDetail: '/app/audio/:submissionId',
  templateDetail: '/app/template/:templateId',
  trainingAsk: '/app/training/ask',
  trainingAskSession: '/app/training/ask/:sessionId',
  recordingReview: '/app/training/recording-review',
  recordingReviewBatch: '/app/training/recording-review/:batchId',
  trainingRubricDetail: '/app/training/rubrics/:rubricId',
  voiceRoleplay: '/app/training/voice-roleplay',
  voiceRoleplaySession: '/app/training/voice-roleplay/:sessionId',
  onboardingMe: '/app/onboarding/me',
  onboardingTrack: '/app/onboarding/track/:trackId',
  onboardingTrackManagement: '/app/onboarding/track-management/:managementTrackId',
  playbooks: '/app/playbooks',
  knowledgeCategory: '/app/knowledge/:categoryId',
  knowledgeBook: '/app/knowledge/book/:bookId',
  profile: '/app/profile',
  settings: '/app/settings',
  settingsTheme: '/app/settings/theme',
  settingsUsersRoles: '/app/settings/users-roles',
  settingsSecurity: '/app/settings/security',
  settingsKnowledgeSync: '/app/settings/knowledge-sync',
  settingsNotifications: '/app/settings/notifications',
  settingsTrackCategories: '/app/settings/track-categories',
  settingsSolutions: '/app/settings/solutions',
  adminUsers: '/app/admin/users',
} as const;

export const buildPath = {
  audioDetail: compile<{ submissionId: string }>(routes.audioDetail),
  templateDetail: compile<{ templateId: string }>(routes.templateDetail),
  trainingAskSession: compile<{ sessionId: string }>(routes.trainingAskSession),
  recordingReviewBatch: compile<{ batchId: string }>(routes.recordingReviewBatch),
  trainingRubricDetail: compile<{ rubricId: string }>(routes.trainingRubricDetail),
  voiceRoleplaySession: compile<{ sessionId: string }>(routes.voiceRoleplaySession),
  onboardingTrack: compile<{ trackId: string }>(routes.onboardingTrack),
  onboardingTrackManagement: compile<{ managementTrackId: string }>(routes.onboardingTrackManagement),
  knowledgeCategory: compile<{ categoryId: string }>(routes.knowledgeCategory),
  knowledgeBook: compile<{ bookId: string }>(routes.knowledgeBook),
};

export const routeLabels: Record<string, string> = {
  [routes.dashboard]: 'Home',
  [routes.audioNew]: 'Quality',
  [routes.trainingAsk]: 'Ask',
  [routes.trainingAskSession]: 'Ask',
  [routes.templateDetail]: 'Template Edit',
  [routes.recordingReview]: 'Recordings',
  [routes.recordingReviewBatch]: 'Recording Batch',
  [routes.trainingRubricDetail]: 'Training Rubric',
  [routes.voiceRoleplay]: 'Senario',
  [routes.voiceRoleplaySession]: 'Senario Session',
  [routes.onboardingMe]: 'Onboard',
  [routes.onboardingTrack]: 'Track Detail',
  [routes.onboardingTrackManagement]: 'Track Edit',
  [routes.playbooks]: 'Knowledge',
  [routes.knowledgeCategory]: 'Knowledge',
  [routes.knowledgeBook]: 'Book Detail',
  [routes.profile]: 'Profile',
  [routes.settings]: 'Settings',
  [routes.settingsTheme]: 'Theme',
  [routes.settingsUsersRoles]: 'Users & Roles',
  [routes.settingsSecurity]: 'Security',
  [routes.settingsKnowledgeSync]: 'Knowledge Sync',
  [routes.settingsNotifications]: 'Notifications',
  [routes.settingsTrackCategories]: 'Track Categories',
  [routes.settingsSolutions]: 'Solutions',
  [routes.adminUsers]: 'Users & Roles',
};
