import type { AudioSubmission, ScorecardResult, ScorecardTemplate, Transcript } from './types';

export const topics = [
  { value: 'product_pitch', label: 'Product Pitch' },
  { value: 'promotion_pitch', label: 'Promotion Pitch' },
  { value: 'competitor_handling', label: 'Competitor Handling' },
  { value: 'compliance_call', label: 'Compliance Call' },
  { value: 'seo_organizer', label: 'SEO Organizer' },
  { value: 'prohibited_answer', label: 'Prohibited Answer' },
  { value: 'advertising_claim', label: 'Advertising Claim Review' },
];

export const customerSegments = [
  { value: 'sme', label: 'SME' },
  { value: 'enterprise', label: 'Enterprise' },
  { value: 'retail', label: 'Retail' },
  { value: 'healthcare', label: 'Healthcare' },
];

export const products = [
  { value: 'product-a', label: 'Product A' },
  { value: 'product-b', label: 'Product B' },
];

export const scorecardTemplates: ScorecardTemplate[] = [
  {
    id: 'sct-promotion-sme-th-v1',
    name: 'Promotion Pitch - SME Thailand',
    version: 1,
    status: 'published',
    topic: 'promotion_pitch',
    customerSegment: 'sme',
    product: 'product-a',
    region: 'th',
    language: 'th',
    effectiveDate: '2026-05-01',
    expiryDate: '2026-06-30',
    totalWeight: 100,
    sections: [
      {
        id: 'opening',
        label: 'Opening',
        weight: 10,
        items: [
          {
            id: 'intro-name-company',
            label: 'แนะนำตัวและบริษัทครบ',
            type: 'required_semantic',
            weight: 5,
            severity: 'medium',
            expectedEvidence: 'sales กล่าวชื่อและบริษัทช่วงต้นสาย',
          },
          {
            id: 'call-purpose',
            label: 'แจ้งวัตถุประสงค์การโทร',
            type: 'required_semantic',
            weight: 5,
            severity: 'medium',
            expectedEvidence: 'sales บอกว่าติดต่อมาเพื่อแนะนำโปรโมชัน',
          },
        ],
      },
      {
        id: 'discovery',
        label: 'Discovery',
        weight: 25,
        items: [
          {
            id: 'pain-point',
            label: 'ซักถาม pain point',
            type: 'quality_semantic',
            weight: 15,
            severity: 'high',
            expectedEvidence: 'sales ถามปัญหาและบริบทก่อนเสนอขาย',
          },
          {
            id: 'budget-qualification',
            label: 'ถามงบประมาณหรือเงื่อนไขการตัดสินใจ',
            type: 'quality_semantic',
            weight: 10,
            severity: 'medium',
            expectedEvidence: 'sales qualify budget หรือ decision process',
          },
        ],
      },
      {
        id: 'promotion-compliance',
        label: 'Promotion Compliance',
        weight: 30,
        items: [
          {
            id: 'promo-terms',
            label: 'แจ้งเงื่อนไขโปรโมชันครบ',
            type: 'conditional_required',
            weight: 15,
            severity: 'critical',
            expectedEvidence: 'เมื่อพูดถึงโปรโมชัน ต้องแจ้งระยะเวลาและเงื่อนไข',
          },
          {
            id: 'no-overclaim',
            label: 'ไม่กล่าวอ้างเกินจริง',
            type: 'negative_phrase',
            weight: 15,
            severity: 'critical',
            expectedEvidence: 'ไม่มี claim เกินจริงหรือคำรับประกันที่ playbook ไม่อนุญาต',
          },
        ],
      },
      {
        id: 'professionalism',
        label: 'Professionalism',
        weight: 35,
        items: [
          {
            id: 'clear-pitch',
            label: 'Pitch เป็นลำดับและเข้าใจง่าย',
            type: 'quality_semantic',
            weight: 20,
            severity: 'medium',
            expectedEvidence: 'มี structure ชัดเจนและโยงกับลูกค้า',
          },
          {
            id: 'no-rude-word',
            label: 'ไม่ใช้คำหยาบหรือกดดันลูกค้า',
            type: 'negative_phrase',
            weight: 15,
            severity: 'critical',
            expectedEvidence: 'ไม่มีคำหยาบหรือภาษากดดัน',
          },
        ],
      },
    ],
  },
  {
    id: 'sct-product-enterprise-th-v1',
    name: 'Product Pitch - Enterprise Thailand',
    version: 1,
    status: 'published',
    topic: 'product_pitch',
    customerSegment: 'enterprise',
    product: 'product-a',
    region: 'th',
    language: 'th',
    effectiveDate: '2026-05-01',
    totalWeight: 100,
    sections: [
      {
        id: 'enterprise-discovery',
        label: 'Enterprise Discovery',
        weight: 40,
        items: [
          {
            id: 'stakeholders',
            label: 'ถามผู้มีส่วนเกี่ยวข้องและ decision process',
            type: 'quality_semantic',
            weight: 20,
            severity: 'high',
            expectedEvidence: 'sales ถาม decision process และ stakeholder',
          },
          {
            id: 'integration-risk',
            label: 'ถามความกังวลด้าน integration',
            type: 'quality_semantic',
            weight: 20,
            severity: 'high',
            expectedEvidence: 'sales ถามระบบเดิมหรือ integration concern',
          },
        ],
      },
    ],
  },
  {
    id: 'sct-article-seo-claim-th-v1',
    name: 'Article SEO + Legal Claim Review - Thailand',
    version: 1,
    status: 'published',
    topic: 'seo_organizer',
    customerSegment: 'sme',
    product: 'product-a',
    region: 'th',
    language: 'th',
    effectiveDate: '2026-05-01',
    totalWeight: 100,
    sections: [
      {
        id: 'seo-structure',
        label: 'SEO Organizer',
        weight: 35,
        items: [
          {
            id: 'search-intent',
            label: 'ตรง search intent และกลุ่มเป้าหมาย',
            type: 'seo_semantic',
            weight: 15,
            severity: 'medium',
            expectedEvidence: 'บทความมี keyword intent, audience และ use case ที่ตรงกับ segment',
          },
          {
            id: 'content-structure',
            label: 'โครงบทความอ่านง่ายและมี heading ครบ',
            type: 'seo_semantic',
            weight: 20,
            severity: 'medium',
            expectedEvidence: 'มี title, H2/H3, summary, CTA และ internal link guideline',
          },
        ],
      },
      {
        id: 'legal-safety',
        label: 'Legal and Advertising Safety',
        weight: 45,
        items: [
          {
            id: 'forbidden-answer',
            label: 'ไม่มีคำตอบห้ามหรือคำแนะนำที่เสี่ยงฟ้องร้อง',
            type: 'prohibited_answer',
            weight: 20,
            severity: 'critical',
            expectedEvidence: 'ไม่พบคำตอบที่ห้ามใช้ เช่น รับประกันผล บิดเบือนราคา หรือให้คำแนะนำเกินขอบเขต',
          },
          {
            id: 'no-exaggerated-claim',
            label: 'ไม่โฆษณาเกินจริงหรือ claim เกิน source',
            type: 'legal_claim',
            weight: 25,
            severity: 'critical',
            expectedEvidence: 'ทุก claim สำคัญต้องมี source จาก Playbook หรือ approved policy',
          },
        ],
      },
      {
        id: 'brand-fit',
        label: 'Brand Fit',
        weight: 20,
        items: [
          {
            id: 'tone-consistency',
            label: 'น้ำเสียงและ CTA สอดคล้องกับ brand guideline',
            type: 'quality_semantic',
            weight: 20,
            severity: 'low',
            expectedEvidence: 'ใช้ tone ที่เป็นมืออาชีพ ไม่กดดัน และไม่สร้างความเข้าใจผิด',
          },
        ],
      },
    ],
  },
];

export const mockSubmission: AudioSubmission = {
  id: 'asub_001',
  status: 'needs_review',
  type: 'sales_call_review',
  topic: 'promotion_pitch',
  customerSegment: 'sme',
  product: 'product-a',
  region: 'th',
  language: 'th',
  scorecardTemplateId: 'sct-promotion-sme-th-v1',
  title: 'Pitch โปร Q2 กับร้านค้ารายย่อย',
  notes: 'mock call จาก training session',
  createdBy: 'user_sales_001',
  createdAt: '2026-05-16T10:00:00Z',
};

export const mockTranscript: Transcript = {
  submissionId: 'asub_001',
  language: 'th',
  durationSec: 182,
  utterances: [
    {
      id: 'utt_001',
      speaker: 'sales',
      startMs: 1200,
      endMs: 5200,
      text: 'สวัสดีครับ ผมสมชายจากบริษัท SaleSync โทรมาแนะนำโปรโมชันไตรมาสนี้ครับ',
      confidence: 0.92,
    },
    {
      id: 'utt_002',
      speaker: 'customer',
      startMs: 5500,
      endMs: 8200,
      text: 'โปรนี้ลดถึงเมื่อไหร่ครับ',
      confidence: 0.89,
    },
    {
      id: 'utt_003',
      speaker: 'sales',
      startMs: 8600,
      endMs: 15100,
      text: 'โปรนี้ช่วยลดต้นทุนได้เยอะครับ และสมัครวันนี้จะได้ราคาพิเศษทันที',
      confidence: 0.87,
    },
    {
      id: 'utt_004',
      speaker: 'customer',
      startMs: 15600,
      endMs: 19800,
      text: 'แล้วต้องใช้ขั้นต่ำกี่เดือนครับ',
      confidence: 0.9,
    },
  ],
};

export const mockScorecard: ScorecardResult = {
  id: 'scr_001',
  submissionId: 'asub_001',
  templateId: 'sct-promotion-sme-th-v1',
  status: 'needs_review',
  totalScore: 70,
  riskLevel: 'medium',
  summary: 'พูดเปิดสายดีและนำเสนอโปรโมชันชัด แต่แจ้งเงื่อนไขไม่ครบและยังซัก pain point ไม่พอ',
  sections: [
    {
      id: 'opening',
      label: 'Opening',
      score: 9,
      maxScore: 10,
      items: [
        {
          id: 'intro-name-company',
          label: 'แนะนำตัวและบริษัทครบ',
          status: 'passed',
          score: 5,
          maxScore: 5,
          severity: 'medium',
          evidence: [
            {
              utteranceId: 'utt_001',
              speaker: 'sales',
              startMs: 1200,
              endMs: 5200,
              text: 'สวัสดีครับ ผมสมชายจากบริษัท SaleSync...',
            },
          ],
          recommendation: null,
        },
        {
          id: 'call-purpose',
          label: 'แจ้งวัตถุประสงค์การโทร',
          status: 'passed',
          score: 4,
          maxScore: 5,
          severity: 'medium',
          evidence: [
            {
              utteranceId: 'utt_001',
              speaker: 'sales',
              startMs: 1200,
              endMs: 5200,
              text: 'โทรมาแนะนำโปรโมชันไตรมาสนี้ครับ',
            },
          ],
          recommendation: null,
        },
      ],
    },
    {
      id: 'discovery',
      label: 'Discovery',
      score: 11,
      maxScore: 25,
      items: [
        {
          id: 'pain-point',
          label: 'ซักถาม pain point',
          status: 'partial',
          score: 7,
          maxScore: 15,
          severity: 'high',
          evidence: [],
          recommendation: 'ควรถามปัญหาปัจจุบันก่อนเสนอโปรโมชัน เช่น ต้นทุนสูงจากส่วนใด หรือใช้เครื่องมืออะไรอยู่',
        },
        {
          id: 'budget-qualification',
          label: 'ถามงบประมาณหรือเงื่อนไขการตัดสินใจ',
          status: 'partial',
          score: 4,
          maxScore: 10,
          severity: 'medium',
          evidence: [],
          recommendation: 'ควรถามงบประมาณและเงื่อนไขอนุมัติ เพื่อแยกคนที่มีงบจริงกับคนที่แค่สนใจราคา',
        },
      ],
    },
    {
      id: 'promotion-compliance',
      label: 'Promotion Compliance',
      score: 18,
      maxScore: 30,
      items: [
        {
          id: 'promo-terms',
          label: 'แจ้งเงื่อนไขโปรโมชันครบ',
          status: 'failed',
          score: 0,
          maxScore: 15,
          severity: 'critical',
          evidence: [],
          recommendation: 'ถ้าพูดถึงโปรโมชัน ต้องแจ้งวันหมดอายุ เงื่อนไขการรับสิทธิ์ และข้อจำกัดให้ครบ',
        },
        {
          id: 'no-overclaim',
          label: 'ไม่กล่าวอ้างเกินจริง',
          status: 'passed',
          score: 15,
          maxScore: 15,
          severity: 'critical',
          evidence: [
            {
              utteranceId: 'utt_003',
              speaker: 'sales',
              startMs: 8600,
              endMs: 15100,
              text: 'โปรนี้ช่วยลดต้นทุนได้เยอะครับ...',
            },
          ],
          recommendation: null,
        },
      ],
    },
    {
      id: 'professionalism',
      label: 'Professionalism',
      score: 35,
      maxScore: 35,
      items: [
        {
          id: 'clear-pitch',
          label: 'Pitch เป็นลำดับและเข้าใจง่าย',
          status: 'passed',
          score: 20,
          maxScore: 20,
          severity: 'medium',
          evidence: [
            {
              utteranceId: 'utt_003',
              speaker: 'sales',
              startMs: 8600,
              endMs: 15100,
              text: 'โปรนี้ช่วยลดต้นทุนได้เยอะครับ...',
            },
          ],
          recommendation: null,
        },
        {
          id: 'no-rude-word',
          label: 'ไม่ใช้คำหยาบหรือกดดันลูกค้า',
          status: 'passed',
          score: 15,
          maxScore: 15,
          severity: 'critical',
          evidence: [],
          recommendation: null,
        },
      ],
    },
  ],
  review: {
    reviewedBy: null,
    reviewedAt: null,
    overrideCount: 0,
  },
};
