import type { LiveMessage, MeetingRoom, Persona, Session } from './types';

export const initialPersonas: Persona[] = [
  {
    id: 'persona-non-tech',
    name: 'คุณเมย์',
    subtitle: 'Non-tech Owner',
    company: 'Local Retail Group',
    difficulty: 'easy',
    description: 'เจ้าของร้านที่สนใจสินค้า แต่ไม่เข้าใจศัพท์เทคนิค ต้องอธิบายให้เห็นภาพง่ายและเชื่อมกับงานหน้าร้าน',
    traits: ['non-tech', 'friendly', 'needs example'],
    goal: 'เข้าใจ value และเห็นขั้นตอนเริ่มใช้งานที่ไม่ซับซ้อน',
    objection: 'กลัวทีมใช้งานไม่เป็นและเสียเวลาติดตั้ง',
    status: 'published',
    sessions: 8,
    avatar: 'ม',
  },
  {
    id: 'persona-budget',
    name: 'คุณธันวา',
    subtitle: 'Value Hunter',
    company: 'SME Procurement',
    difficulty: 'medium',
    description: 'สนใจ ROI และต้นทุนรวมมากเป็นพิเศษ ต่อรองเก่งและต้องการหลักฐานก่อนตัดสินใจ',
    traits: ['price-sensitive', 'roi-first', 'practical'],
    goal: 'เปรียบเทียบความคุ้มค่าและลดความกังวลเรื่องค่าใช้จ่ายแฝง',
    objection: 'บอกว่างบเยอะ แต่จริง ๆ ต้องขออนุมัติ CFO',
    status: 'published',
    sessions: 12,
    avatar: 'ธ',
  },
  {
    id: 'persona-skeptic',
    name: 'คุณกร',
    subtitle: 'The Skeptic',
    company: 'Enterprise Tech Corp.',
    difficulty: 'hard',
    description: 'ต้องการข้อมูลหนักและ social proof ไม่เชื่อคำขายที่กว้างเกินไป และจับ overclaim ได้เร็ว',
    traits: ['data-driven', 'resistant', 'technical'],
    goal: 'พิสูจน์ความน่าเชื่อถือโดยไม่พูดเกินจริงหรือผิด compliance',
    objection: 'ใช้คู่แข่งอยู่และมองว่า Pitchsmith ยังไม่มี proof เพียงพอ',
    status: 'published',
    sessions: 6,
    avatar: 'ก',
  },
  {
    id: 'persona-distracted',
    name: 'คุณแพรว',
    subtitle: 'Off-topic Buyer',
    company: 'Lifestyle Commerce',
    difficulty: 'medium',
    description: 'ชอบออกนอกเรื่องและเปลี่ยนประเด็นเร็ว ต้องดึงกลับเข้ากรอบ discovery โดยไม่แข็งเกินไป',
    traits: ['distracted', 'talkative', 'needs structure'],
    goal: 'คุมบทสนทนาให้กลับมาที่ pain point และ next step',
    objection: 'เล่าเรื่องธุรกิจเยอะ แต่ไม่ตอบเรื่อง budget และ timeline ตรง ๆ',
    status: 'draft',
    sessions: 3,
    avatar: 'พ',
  },
];

export const initialMeetingRooms: MeetingRoom[] = [
  {
    id: 'room-procurement-committee',
    name: 'Procurement Committee',
    description: '2 manager และ 1 technical stakeholder สำหรับดีลที่ต้องขออนุมัติหลายฝ่าย',
    personaIds: ['persona-budget', 'persona-skeptic', 'persona-distracted'],
    scenario: 'Enterprise procurement review',
    status: 'published',
  },
  {
    id: 'room-sme-store',
    name: 'SME Store Buying Team',
    description: 'เจ้าของร้านและทีมปฏิบัติการที่ต้องเห็นภาพ onboarding ง่ายและคุ้มค่า',
    personaIds: ['persona-non-tech', 'persona-budget'],
    scenario: 'SME product adoption',
    status: 'published',
  },
];

export const initialSessions: Session[] = [
  {
    id: 'vr-001',
    personaIds: ['persona-budget', 'persona-skeptic'],
    meetingRoomId: 'room-procurement-committee',
    title: 'Q2 Promotion Discovery',
    date: 'วันนี้ 10:42',
    duration: '12m',
    score: 84,
    turns: 18,
    outcome: 'ถาม budget truth ได้ดีขึ้น แต่ยังควรปิด next step ให้ชัด',
    meetingGoal: 'ค้นหา budget truth, decision process และเงื่อนไขอนุมัติของโปร Q2 โดยไม่ overclaim เรื่องผลลัพธ์',
    improvementSuggestion: 'ปิด next step ด้วย owner, timeline และหลักฐานที่ต้องส่งต่อให้ทีม procurement ชัดกว่านี้',
    knowledgeAcquired: [
      {
        id: 'ka-q2-promo-terms',
        title: 'Q2 Promotion Terms for SME',
        summary: 'เงื่อนไขโปรโมชัน Q2 สำหรับร้านค้า SME, วันหมดอายุ, ยอดขั้นต่ำ และข้อจำกัดสิทธิ์ที่ต้องแจ้งลูกค้า',
        source: 'Playbook / Promotion / Q2 SME',
        type: 'playbook',
        focus: 'ใช้ตอบคำถาม eligibility และป้องกันการแจ้งเงื่อนไขไม่ครบ',
        readTime: '4 min read',
        favorited: true,
      },
      {
        id: 'ka-claim-guardrail',
        title: 'Promotion Claim Guardrail',
        summary: 'คำตอบต้องห้าม เช่น รับประกันยอดขาย หรือการันตี conversion โดยไม่มี evidence รองรับ',
        source: 'Compliance Guardrail / Advertising Claim',
        type: 'guardrail',
        focus: 'ใช้ตรวจประโยค overclaim ระหว่างตอบ objection',
        readTime: '3 min read',
      },
      {
        id: 'ka-budget-truth',
        title: 'Budget Truth Discovery Script',
        summary: 'ตัวอย่างคำถามเพื่อแยก budget จริง, approval owner และ decision timeline ก่อนเสนอ next step',
        source: 'Sales Playbook / Discovery',
        type: 'faq',
        focus: 'ช่วยถาม decision process ให้ชัดขึ้นในรอบถัดไป',
        readTime: '5 min read',
      },
    ],
    conversation: [
      {
        id: 'vr-001-c1',
        speakerType: 'persona',
        personaId: 'persona-budget',
        timestamp: '00:00',
        text: 'โปร Q2 สำหรับ SME ใช้กับร้านค้ารายย่อยได้ไหม และต้องแจ้งเงื่อนไขอะไรกับลูกค้าบ้าง',
      },
      {
        id: 'vr-001-c2',
        speakerType: 'seller',
        timestamp: '00:38',
        text: 'ใช้ได้กับร้านค้ารายย่อยที่เข้าเกณฑ์ SME และต้องแจ้งวันหมดอายุ ยอดขั้นต่ำ และข้อจำกัดสิทธิ์ให้ครบครับ',
        feedback: 'ตอบเงื่อนไขได้ครบและไม่ overclaim',
      },
      {
        id: 'vr-001-c3',
        speakerType: 'persona',
        personaId: 'persona-skeptic',
        timestamp: '01:24',
        text: 'ถ้าลูกค้าถามว่ารับประกันยอดขายเพิ่มไหม คุณจะตอบยังไง',
      },
      {
        id: 'vr-001-c4',
        speakerType: 'seller',
        timestamp: '02:05',
        text: 'ผมจะไม่รับประกันยอดขายครับ แต่จะอธิบายว่าโปรช่วยเพิ่มแรงจูงใจในการทดลองซื้อ และควรวัดผลจาก conversion กับ basket size',
        feedback: 'ดี: เลี่ยงคำตอบต้องห้ามและเสนอ metric สำหรับติดตามผล',
      },
    ],
    competencies: { Discovery: 82, Objection: 78, Value: 88, Compliance: 86, Closing: 76 },
    strengths: ['ยืนยันเงื่อนไขโปรโมชันได้ครบ', 'เชื่อม ROI กับ pain point ของลูกค้าได้ดี'],
    growth: ['ควรถาม decision process ให้ชัดขึ้น', 'ปิด next step พร้อม timeline ให้เร็วกว่าเดิม'],
  },
  {
    id: 'vr-002',
    personaIds: ['persona-skeptic'],
    title: 'Competitor Objection',
    date: 'เมื่อวาน 16:10',
    duration: '15m',
    score: 71,
    turns: 22,
    outcome: 'ตอบ technical proof ได้ แต่มีประโยคที่เสี่ยง overclaim',
    meetingGoal: 'รับมือคำถามคู่แข่งด้วย proof ที่ตรวจสอบได้ และหลีกเลี่ยง claim ว่าดีกว่าทุกด้าน',
    improvementSuggestion: 'ลดคำพูดเชิงการันตี และอ้าง evidence เฉพาะกรณีที่มี playbook source รองรับเท่านั้น',
    knowledgeAcquired: [
      {
        id: 'ka-competitor-positioning',
        title: 'Competitor Positioning Guide',
        summary: 'วิธีตอบเปรียบเทียบคู่แข่งโดยชี้ capability ที่ตรวจสอบได้ ไม่พูดว่าดีกว่าทุกด้าน',
        source: 'Playbook / Competitor',
        type: 'playbook',
        focus: 'ใช้ตอบ objection คู่แข่งแบบไม่ overclaim',
        readTime: '6 min read',
      },
      {
        id: 'ka-pilot-proof',
        title: 'Pilot Result Citation Rules',
        summary: 'แนวทางอ้างผล pilot และ case study ให้ชัดว่าเป็นบริบทเฉพาะ ไม่ใช่ผลลัพธ์ทั่วไป',
        source: 'Compliance Guardrail / Evidence',
        type: 'guardrail',
        focus: 'ลดความเสี่ยงจาก claim ผลลัพธ์เกินจริง',
        readTime: '4 min read',
      },
    ],
    conversation: [
      {
        id: 'vr-002-c1',
        speakerType: 'persona',
        personaId: 'persona-skeptic',
        timestamp: '00:00',
        text: 'คู่แข่งเราบอกว่าระบบเขาแม่นกว่าและ onboarding ได้เร็วกว่า คุณมี proof อะไร',
      },
      {
        id: 'vr-002-c2',
        speakerType: 'seller',
        timestamp: '00:51',
        text: 'จาก pilot ที่มีข้อมูลเทียบเคียง ทีมลดเวลา roleplay review ได้ประมาณ 30% แต่ผมขอส่ง case study ที่ตรงอุตสาหกรรมคุณให้ดูเพิ่ม',
        feedback: 'ควรระบุว่าเป็น pilot เฉพาะบริบท ไม่ใช่ผลลัพธ์ทั่วไป',
      },
      {
        id: 'vr-002-c3',
        speakerType: 'persona',
        personaId: 'persona-skeptic',
        timestamp: '02:18',
        text: 'ถ้าผลลัพธ์ขึ้นกับบริบท แล้วทำไมผมต้องเชื่อว่า Pitchsmith ดีกว่า solution ที่ทีมผมใช้อยู่',
      },
      {
        id: 'vr-002-c4',
        speakerType: 'seller',
        timestamp: '03:04',
        text: 'ผมจะไม่บอกว่าดีกว่าทุกด้านครับ แต่ Pitchsmith ต่างตรงที่จำลองหลาย stakeholder และวัด objection, product knowledge, confidence จาก playbook จริงขององค์กร',
        feedback: 'ดี: ลด overclaim และแยก positioning จากคู่แข่งด้วย capability ที่ตรวจสอบได้',
      },
      {
        id: 'vr-002-c5',
        speakerType: 'persona',
        personaId: 'persona-skeptic',
        timestamp: '05:42',
        text: 'แล้วถ้าเซลล์ตอบผิดจาก policy หรือโปรโมชันหมดอายุ ระบบจะป้องกันยังไง',
      },
      {
        id: 'vr-002-c6',
        speakerType: 'seller',
        timestamp: '06:31',
        text: 'ระบบจะใช้ published playbook และ guardrail ที่ระบุ effective date กับ expiry date ถ้าไม่มี source รองรับควร abstain หรือแนะนำให้ตรวจสอบกับ owner ก่อนครับ',
        feedback: 'ดีขึ้น: อ้าง governance ชัด แต่ควรปิดด้วยตัวอย่าง report ที่ manager จะเห็น',
      },
      {
        id: 'vr-002-c7',
        speakerType: 'persona',
        personaId: 'persona-skeptic',
        timestamp: '09:10',
        text: 'ขอ next step ที่ไม่เสียเวลาทีมผมมาก คุณจะเสนออะไร',
      },
      {
        id: 'vr-002-c8',
        speakerType: 'seller',
        timestamp: '10:02',
        text: 'ผมขอใช้ sample playbook 1 ชุดกับ persona คู่แข่ง 2 แบบ แล้วส่ง summary score, risk phrase และ coaching focus ให้คุณดูภายใน 3 วันครับ',
        feedback: 'ควรระบุ owner และ format ของ artifact ให้ชัด เช่น PDF summary หรือ dashboard link',
      },
    ],
    competencies: { Discovery: 70, Objection: 74, Value: 76, Compliance: 62, Closing: 68 },
    strengths: ['รับมือคำถามคู่แข่งได้ต่อเนื่อง', 'ใช้ evidence ช่วยอธิบายได้'],
    growth: ['ลดประโยคที่ฟังเหมือนการันตีผลลัพธ์', 'สรุป next step ให้สั้นและชัด'],
  },
  {
    id: 'vr-003',
    personaIds: ['persona-non-tech', 'persona-distracted'],
    meetingRoomId: 'room-sme-store',
    title: 'Product Demo for SME',
    date: '15 พ.ค. 14:05',
    duration: '9m',
    score: 78,
    turns: 14,
    outcome: 'ยกตัวอย่างเข้าใจง่าย แต่ยังถาม pain point ไม่ครบ',
    meetingGoal: 'อธิบาย product demo ให้ non-tech เข้าใจ และค้นหา pain point ก่อนเข้าสู่ proposal',
    improvementSuggestion: 'ถาม pain point ปัจจุบันอย่างน้อย 2 รอบก่อนเสนอ feature เพื่อให้ demo ไม่กลายเป็นการบรรยายฝ่ายเดียว',
    knowledgeAcquired: [
      {
        id: 'ka-non-tech-onboarding',
        title: 'Non-tech Onboarding Talk Track',
        summary: 'คำอธิบาย onboarding แบบไม่ใช้ศัพท์เทคนิคสำหรับเจ้าของร้านและทีมปฏิบัติการ',
        source: 'Playbook / SME Onboarding',
        type: 'playbook',
        focus: 'ช่วยอธิบาย value ให้ง่ายและเชื่อมกับงานหน้าร้าน',
        readTime: '5 min read',
      },
      {
        id: 'ka-demo-discovery',
        title: 'Demo Discovery Checklist',
        summary: 'คำถามก่อน demo เพื่อเข้าใจงานปัจจุบัน, bottleneck และ success criteria ของลูกค้า',
        source: 'FAQ / Demo Prep',
        type: 'faq',
        focus: 'ป้องกัน demo ที่พูด feature อย่างเดียวโดยไม่ผูก pain point',
        readTime: '3 min read',
      },
    ],
    conversation: [
      {
        id: 'vr-003-c1',
        speakerType: 'persona',
        personaId: 'persona-non-tech',
        timestamp: '00:00',
        text: 'ทีมร้านผมไม่ค่อยเก่งเทค ถ้าใช้ระบบนี้จะเริ่มยังไง',
      },
      {
        id: 'vr-003-c2',
        speakerType: 'seller',
        timestamp: '00:44',
        text: 'เริ่มจาก template บทสนทนาสั้น ๆ แล้วให้ทีมซ้อมกับ AI ก่อน จากนั้น manager จะเห็นคะแนนและคำแนะนำรายคนครับ',
        feedback: 'เข้าใจง่าย แต่ควรถามต่อว่าปัจจุบันทีมติดตรงขั้นตอนไหน',
      },
    ],
    competencies: { Discovery: 68, Objection: 72, Value: 84, Compliance: 82, Closing: 74 },
    strengths: ['อธิบายศัพท์ยากด้วยตัวอย่างง่าย', 'รักษาจังหวะบทสนทนาได้ดี'],
    growth: ['ถาม pain point ปัจจุบันให้ลึกขึ้น', 'สรุป action หลัง demo ให้ครบ'],
  },
];

export const liveMessages: LiveMessage[] = [
  {
    speaker: 'AI Customer',
    align: 'left',
    text: 'ข้อเสนอน่าสนใจครับ แต่ผมยังไม่เห็นชัดว่า Pitchsmith จะช่วยทีมขายที่ไม่ถนัดเทคโนโลยีได้ยังไง',
  },
  {
    speaker: 'You',
    align: 'right',
    text: 'ทีมเริ่มจาก playbook สั้น ๆ และระบบจะช่วยประเมินบทสนทนาให้เห็นว่าควรปรับตรงไหนในแต่ละครั้งครับ',
  },
  {
    speaker: 'AI Customer',
    align: 'left',
    text: 'แล้วถ้าผมไม่มีเวลาสอนทีมเอง ระบบช่วยลดเวลาการ onboard ได้จริงแค่ไหน',
  },
];
