import type { LiveMessage, MeetingRoom, Persona, Session } from './types';

export const initialPersonas: Persona[] = [
  {
    id: 'persona-non-tech',
    name: 'คุณเมย์',
    subtitle: 'Non-tech Owner',
    company: 'Local Retail Group',
    difficulty: 'easy',
    description: 'เจ้าของร้านที่สนใจสินค้า แต่ไม่เข้าใจศัพท์เทคนิค ต้องอธิบายให้เห็นภาพง่ายและเชื่อมกับงานหน้าร้าน',
    traits: ['non-tech', 'friendly', 'needs example'],
    goal: 'เข้าใจ value และเห็นขั้นตอนเริ่มใช้งานที่ไม่ซับซ้อน',
    objection: 'กลัวทีมใช้งานไม่เป็นและเสียเวลาติดตั้ง',
    status: 'published',
    sessions: 8,
    avatar: 'ม',
  },
  {
    id: 'persona-budget',
    name: 'คุณธันวา',
    subtitle: 'Value Hunter',
    company: 'SME Procurement',
    difficulty: 'medium',
    description: 'สนใจ ROI และต้นทุนรวมมากเป็นพิเศษ ต่อรองเก่งและต้องการหลักฐานก่อนตัดสินใจ',
    traits: ['price-sensitive', 'roi-first', 'practical'],
    goal: 'เปรียบเทียบความคุ้มค่าและลดความกังวลเรื่องค่าใช้จ่ายแฝง',
    objection: 'บอกว่างบเยอะ แต่จริง ๆ ต้องขออนุมัติ CFO',
    status: 'published',
    sessions: 12,
    avatar: 'ธ',
  },
  {
    id: 'persona-skeptic',
    name: 'คุณกร',
    subtitle: 'The Skeptic',
    company: 'Enterprise Tech Corp.',
    difficulty: 'hard',
    description: 'ต้องการข้อมูลหนักและ social proof ไม่เชื่อคำขายที่กว้างเกินไป และจับ overclaim ได้เร็ว',
    traits: ['data-driven', 'resistant', 'technical'],
    goal: 'พิสูจน์ความน่าเชื่อถือโดยไม่พูดเกินจริงหรือผิด compliance',
    objection: 'ใช้คู่แข่งอยู่และมองว่า Pitchsmith ยังไม่มี proof เพียงพอ',
    status: 'published',
    sessions: 6,
    avatar: 'ก',
  },
  {
    id: 'persona-distracted',
    name: 'คุณแพรว',
    subtitle: 'Off-topic Buyer',
    company: 'Lifestyle Commerce',
    difficulty: 'medium',
    description: 'ชอบออกนอกเรื่องและเปลี่ยนประเด็นเร็ว ต้องดึงกลับเข้ากรอบ discovery โดยไม่แข็งเกินไป',
    traits: ['distracted', 'talkative', 'needs structure'],
    goal: 'คุมบทสนทนาให้กลับมาที่ pain point และ next step',
    objection: 'เล่าเรื่องธุรกิจเยอะ แต่ไม่ตอบเรื่อง budget และ timeline ตรง ๆ',
    status: 'draft',
    sessions: 3,
    avatar: 'พ',
  },
];

export const initialMeetingRooms: MeetingRoom[] = [
  {
    id: 'room-procurement-committee',
    name: 'Procurement Committee',
    description: '2 manager และ 1 technical stakeholder สำหรับดีลที่ต้องขออนุมัติหลายฝ่าย',
    personaIds: ['persona-budget', 'persona-skeptic', 'persona-distracted'],
    scenario: 'Enterprise procurement review',
    status: 'published',
  },
  {
    id: 'room-sme-store',
    name: 'SME Store Buying Team',
    description: 'เจ้าของร้านและทีมปฏิบัติการที่ต้องเห็นภาพ onboarding ง่ายและคุ้มค่า',
    personaIds: ['persona-non-tech', 'persona-budget'],
    scenario: 'SME product adoption',
    status: 'published',
  },
];

export const initialSessions: Session[] = [
  {
    id: 'vr-001',
    personaIds: ['persona-budget', 'persona-skeptic'],
    meetingRoomId: 'room-procurement-committee',
    title: 'Q2 Promotion Discovery',
    date: 'วันนี้ 10:42',
    duration: '12m',
    score: 84,
    turns: 18,
    outcome: 'ถาม budget truth ได้ดีขึ้น แต่ยังควรปิด next step ให้ชัด',
    meetingGoal: 'ค้นหา budget truth, decision process และเงื่อนไขอนุมัติของโปร Q2 โดยไม่ overclaim เรื่องผลลัพธ์',
    improvementSuggestion: 'ปิด next step ด้วย owner, timeline และหลักฐานที่ต้องส่งต่อให้ทีม procurement ชัดกว่านี้',
    conversation: [
      {
        id: 'vr-001-c1',
        speakerType: 'persona',
        personaId: 'persona-budget',
        timestamp: '00:00',
        text: 'โปร Q2 สำหรับ SME ใช้กับร้านค้ารายย่อยได้ไหม และต้องแจ้งเงื่อนไขอะไรกับลูกค้าบ้าง',
      },
      {
        id: 'vr-001-c2',
        speakerType: 'seller',
        timestamp: '00:38',
        text: 'ใช้ได้กับร้านค้ารายย่อยที่เข้าเกณฑ์ SME และต้องแจ้งวันหมดอายุ ยอดขั้นต่ำ และข้อจำกัดสิทธิ์ให้ครบครับ',
        feedback: 'ตอบเงื่อนไขได้ครบและไม่ overclaim',
      },
      {
        id: 'vr-001-c3',
        speakerType: 'persona',
        personaId: 'persona-skeptic',
        timestamp: '01:24',
        text: 'ถ้าลูกค้าถามว่ารับประกันยอดขายเพิ่มไหม คุณจะตอบยังไง',
      },
      {
        id: 'vr-001-c4',
        speakerType: 'seller',
        timestamp: '02:05',
        text: 'ผมจะไม่รับประกันยอดขายครับ แต่จะอธิบายว่าโปรช่วยเพิ่มแรงจูงใจในการทดลองซื้อ และควรวัดผลจาก conversion กับ basket size',
        feedback: 'ดี: เลี่ยงคำตอบต้องห้ามและเสนอ metric สำหรับติดตามผล',
      },
    ],
    competencies: { Discovery: 82, Objection: 78, Value: 88, Compliance: 86, Closing: 76 },
    strengths: ['ยืนยันเงื่อนไขโปรโมชันได้ครบ', 'เชื่อม ROI กับ pain point ของลูกค้าได้ดี'],
    growth: ['ควรถาม decision process ให้ชัดขึ้น', 'ปิด next step พร้อม timeline ให้เร็วกว่าเดิม'],
  },
  {
    id: 'vr-002',
    personaIds: ['persona-skeptic'],
    title: 'Competitor Objection',
    date: 'เมื่อวาน 16:10',
    duration: '15m',
    score: 71,
    turns: 22,
    outcome: 'ตอบ technical proof ได้ แต่มีประโยคที่เสี่ยง overclaim',
    meetingGoal: 'รับมือคำถามคู่แข่งด้วย proof ที่ตรวจสอบได้ และหลีกเลี่ยง claim ว่าดีกว่าทุกด้าน',
    improvementSuggestion: 'ลดคำพูดเชิงการันตี และอ้าง evidence เฉพาะกรณีที่มี playbook source รองรับเท่านั้น',
    conversation: [
      {
        id: 'vr-002-c1',
        speakerType: 'persona',
        personaId: 'persona-skeptic',
        timestamp: '00:00',
        text: 'คู่แข่งเราบอกว่าระบบเขาแม่นกว่าและ onboarding ได้เร็วกว่า คุณมี proof อะไร',
      },
      {
        id: 'vr-002-c2',
        speakerType: 'seller',
        timestamp: '00:51',
        text: 'จาก pilot ที่มีข้อมูลเทียบเคียง ทีมลดเวลา roleplay review ได้ประมาณ 30% แต่ผมขอส่ง case study ที่ตรงอุตสาหกรรมคุณให้ดูเพิ่ม',
        feedback: 'ควรระบุว่าเป็น pilot เฉพาะบริบท ไม่ใช่ผลลัพธ์ทั่วไป',
      },
    ],
    competencies: { Discovery: 70, Objection: 74, Value: 76, Compliance: 62, Closing: 68 },
    strengths: ['รับมือคำถามคู่แข่งได้ต่อเนื่อง', 'ใช้ evidence ช่วยอธิบายได้'],
    growth: ['ลดประโยคที่ฟังเหมือนการันตีผลลัพธ์', 'สรุป next step ให้สั้นและชัด'],
  },
  {
    id: 'vr-003',
    personaIds: ['persona-non-tech', 'persona-distracted'],
    meetingRoomId: 'room-sme-store',
    title: 'Product Demo for SME',
    date: '15 พ.ค. 14:05',
    duration: '9m',
    score: 78,
    turns: 14,
    outcome: 'ยกตัวอย่างเข้าใจง่าย แต่ยังถาม pain point ไม่ครบ',
    meetingGoal: 'อธิบาย product demo ให้ non-tech เข้าใจ และค้นหา pain point ก่อนเข้าสู่ proposal',
    improvementSuggestion: 'ถาม pain point ปัจจุบันอย่างน้อย 2 รอบก่อนเสนอ feature เพื่อให้ demo ไม่กลายเป็นการบรรยายฝ่ายเดียว',
    conversation: [
      {
        id: 'vr-003-c1',
        speakerType: 'persona',
        personaId: 'persona-non-tech',
        timestamp: '00:00',
        text: 'ทีมร้านผมไม่ค่อยเก่งเทค ถ้าใช้ระบบนี้จะเริ่มยังไง',
      },
      {
        id: 'vr-003-c2',
        speakerType: 'seller',
        timestamp: '00:44',
        text: 'เริ่มจาก template บทสนทนาสั้น ๆ แล้วให้ทีมซ้อมกับ AI ก่อน จากนั้น manager จะเห็นคะแนนและคำแนะนำรายคนครับ',
        feedback: 'เข้าใจง่าย แต่ควรถามต่อว่าปัจจุบันทีมติดตรงขั้นตอนไหน',
      },
    ],
    competencies: { Discovery: 68, Objection: 72, Value: 84, Compliance: 82, Closing: 74 },
    strengths: ['อธิบายศัพท์ยากด้วยตัวอย่างง่าย', 'รักษาจังหวะบทสนทนาได้ดี'],
    growth: ['ถาม pain point ปัจจุบันให้ลึกขึ้น', 'สรุป action หลัง demo ให้ครบ'],
  },
];

export const liveMessages: LiveMessage[] = [
  {
    speaker: 'AI Customer',
    align: 'left',
    text: 'ข้อเสนอน่าสนใจครับ แต่ผมยังไม่เห็นชัดว่า Pitchsmith จะช่วยทีมขายที่ไม่ถนัดเทคโนโลยีได้ยังไง',
  },
  {
    speaker: 'You',
    align: 'right',
    text: 'ทีมเริ่มจาก playbook สั้น ๆ และระบบจะช่วยประเมินบทสนทนาให้เห็นว่าควรปรับตรงไหนในแต่ละครั้งครับ',
  },
  {
    speaker: 'AI Customer',
    align: 'left',
    text: 'แล้วถ้าผมไม่มีเวลาสอนทีมเอง ระบบช่วยลดเวลาการ onboard ได้จริงแค่ไหน',
  },
];
